# -*- coding: utf-8 -*-
"""GPBoost-ob-re.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4agWCrSrGWDxXhCjI8mNNkQJIeERaIE

# Import Package
"""

import os
import zipfile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import re
import zipfile

from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from scipy.stats import spearmanr

!pip install gpboost
import gpboost as gpb

"""# Import Google Drive Data"""

from google.colab import files
from google.colab import drive

drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/aiv/gee_data.zip"
extract_to = "/content/gee_data"

os.makedirs(extract_to, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
  zip_ref.extractall(extract_to)

os.listdir(extract_to)

for root, dirs, files in os.walk("/content/gee_data"):
    for file in files[::]:
        print(os.path.join(root, file))

zip_path = "/content/drive/MyDrive/eu-aiv-analysis/ebird_filtered_checklist.zip"
extract_to = "/content/checklist"

os.makedirs(extract_to, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
  zip_ref.extractall(extract_to)

os.listdir(extract_to)

for root, dirs, files in os.walk("/content/checklist"):
    for file in files[::]:
        print(os.path.join(root, file))

!cp -r "/content/drive/MyDrive/aiv/EU_100km_fishnet_simple_by_distance" "/content/EU_100km_fishnet_simple_by_distance"

lc_path = "/content/gee_data/gee_data/land_cover_2016_2022.csv"
era5_2021_path = "/content/gee_data/gee_data/era5_2016_2022/2021_median_combined_result.csv"
era5_2022_path = "/content/gee_data/gee_data/era5_2016_2022/2022_median_combined_result.csv"

fishnet_path = "/content/EU_100km_fishnet_simple_by_distance"

for p in [lc_path, era5_2021_path, era5_2022_path, fishnet_path]:
  print(p, os.path.exists(p))

# Environment Data Processing

lc = pd.read_csv(lc_path)
era5_2021 = pd.read_csv(era5_2021_path)
era5_2022 = pd.read_csv(era5_2022_path)

era5_2021 = era5_2021.rename(columns={"Month": "month_number"})
era5_2022 = era5_2022.rename(columns={"Month": "month_number"})
era5_2021["month_number"] = pd.to_datetime(era5_2021["month_number"]).dt.month
era5_2022["month_number"] = pd.to_datetime(era5_2022["month_number"]).dt.month
era5_2022["year_number"] = 2022
era5_2021["year_number"] = 2021

era5_all = pd.concat([era5_2021, era5_2022], ignore_index=True)
print(len(era5_2021))
print(len(era5_2022))
print(len(era5_all))

env = pd.merge(lc, era5_all, on=["Id","month_number", "year_number"], how="inner")
print(len(lc))
print(len(era5_all))
print(len(env))
print(len(env[env["year_number"] == 2021]))
print(len(env[env["year_number"] == 2022]))
#env.isna().sum()

# Import eBird Checklist

ebird_checklist_paths = []

for root, dirs, files in os.walk("/content/checklist"):
    for file in files[::]:
        ebird_checklist_paths.append(os.path.join(root, file))

ebird_checklist_paths

bird_names = ["Vanellus vanellus", "Anas crecca", "Branta canadensis", "Numenius arquata", "Larus canus", "Chroicocephalus ridibundus"]
bird_names = ["Vanellus vanellus"]
print(bird_names)

# r1: "Accipiter nisus", "Aix galericulata", "Anas acuta", "Anas platyrhynchos", "Anser anser"
# r2: "Ardea alba", "Ardea cinerea", "Arenaria interpres", "Athene noctua", "Aythya ferina"
# r3: "Aythya fuligula", "Branta bernicla", "Branta canadensis", "Bucephala clangula", "Buteo buteo"
# r4: "Calidris alba", "Calidris alpina", "Charadrius hiaticula", "Chroicocephalus ridibundus", "Ciconia ciconia"
# r5: "Columba livia", "Columba palumbus", "Corvus corax", "Corvus cornix", "Cygnus cygnus"
# r6: "Cygnus olor", "Egretta garzetta", "Falco peregrinus", "Falco tinnunculus", "Fringilla montifringilla"
# r7: "Fulica atra", "Gallinago gallinago", "Gallinula chloropus", "Gyps fulvus", "Hirundo rustica"

# r8: "Ichthyaetus melanocephalus", "Larus canus", "Larus fuscus", "Larus marinus", "Larus michahellis"
# r9: "Limosa lapponica", "Limosa limosa", "Mareca penelope", "Mareca strepera", "Motacilla alba"
# r10: "Numenius arquata", "Passer domesticus", "Passer montanus", "Phalacrocorax carbo", "Phasianus colchicus"
# r11: "Phoenicopterus roseus", "Platalea leucorodia", "Plegadis falcinellus", "Pluvialis squatarola", "Podiceps cristatus"
# r12: "Recurvirostra avosetta", "Somateria mollissima", "Spatula clypeata", "Streptopelia decaocto", "Sturnus vulgaris"
# r13: "Tachybaptus ruficollis", "Tadorna tadorna", "Tringa ochropus", "Tringa totanus", "Turdus merula"
# r14: "Vanellus vanellus", "Anas crecca"

bird_names = [
    "Ichthyaetus melanocephalus", "Larus canus", "Larus fuscus", "Larus marinus", "Larus michahellis",
    "Limosa lapponica", "Limosa limosa", "Mareca penelope", "Mareca strepera", "Motacilla alba",
    "Numenius arquata", "Passer domesticus", "Passer montanus", "Phalacrocorax carbo", "Phasianus colchicus",
    "Phoenicopterus roseus", "Platalea leucorodia", "Plegadis falcinellus", "Pluvialis squatarola", "Podiceps cristatus",
    "Recurvirostra avosetta", "Somateria mollissima", "Spatula clypeata", "Streptopelia decaocto", "Sturnus vulgaris",
    "Tachybaptus ruficollis", "Tadorna tadorna", "Tringa ochropus", "Tringa totanus", "Turdus merula",
    "Vanellus vanellus", "Anas crecca"
]
print(bird_names)

for bird_name in bird_names:
  ### load checklist data
  print("bird name: ", bird_name)
  path1 = f"/content/checklist/ebird_filtered_checklist/^{bird_name}_filtered_2019to2022.csv"
  path2 = f"/content/checklist/ebird_filtered_checklist/^{bird_name}_filtered2019to2022.csv"

  if os.path.exists(path1):
      checklist_path = path1
  elif os.path.exists(path2):
      checklist_path = path2
  else:
      raise FileNotFoundError(f"Cannot find checklist file for {bird_name}")

  checklist = pd.read_csv(checklist_path)

  checklist['observation_date'] = pd.to_datetime(checklist['observation_date'])
  checklist['year_number'] = checklist['observation_date'].dt.year
  checklist['month_number'] = checklist['observation_date'].dt.month

  cl_include_cols = ['category','common_name','observation_date','all_species_reported','group_identifier','time_started']
  cl_cols = [col for col in checklist.columns if col not in cl_include_cols]
  checklist = checklist[cl_cols].copy()

  checklist["observation_count"] = pd.to_numeric(checklist["observation_count"].replace("X", 0))
  checklist["locality_type"] = checklist["locality_type"].map({"P": 0, "H": 1}).astype(int)

  protocol_cols = ["Traveling", "Stationary"]
  checklist = checklist[checklist["protocol_type"].isin(protocol_cols)].copy()
  checklist["protocol_type"] = checklist["protocol_type"].map({"Stationary": 0, "Traveling": 1}).astype(int)
  checklist = checklist[checklist["protocol_type"] == 1].copy()

  print("lehgth of checklist : ", len(checklist))
  print("lehgth of checklist in 2019 : ", len(checklist[checklist["year_number"]==2019]))
  print("lehgth of checklist in 2020 : ", len(checklist[checklist["year_number"]==2020]))
  print("lehgth of checklist in 2021 : ", len(checklist[checklist["year_number"]==2021]))
  print("lehgth of checklist in 2022 : ", len(checklist[checklist["year_number"]==2022]))

  ### merge checklist and env data
  df = pd.merge(checklist, env, on=["Id","month_number", "year_number"], how="inner")
  print("Before dropna:", len(df))
  df = df.dropna().reset_index(drop=True)
  print("After dropna:", len(df))

  ### filter data
  oc_q99 = df["observation_count"].quantile(0.99)
  df = df[df["observation_count"] <= oc_q99].copy()
  print("99% cutoff of observation count: ", oc_q99)
  print("rows after cut: ", len(df))

  observer_info = pd.DataFrame(df.groupby("observer_id").size().reset_index())
  observer_info.columns = ["observer_id", "count"]
  orc_q70 = observer_info["count"].quantile(0.7)
  observer_list = observer_info["observer_id"][observer_info["count"] > orc_q70].copy()
  df = df[df["observer_id"].isin(observer_list)]
  print(f"70% cutoff of observer count ;{orc_q70}")
  print("number of observers: ", len(observer_list))
  print("rows after cut: ", len(df))

  id_info = pd.DataFrame(df.groupby("Id").size().reset_index())
  id_info.columns = ["Id", "count"]
  idc_q50 = id_info["count"].quantile(0.5)
  id_list = id_info["Id"][id_info["count"] > idc_q50]
  df = df[df["Id"].isin(id_list)]
  print(f"50% cutoff of Id count ;{idc_q50}")
  print("number of Ids: ", len(id_list))
  print("rows after cut: ", len(df))

  df['sample_id'] = range(1,len(df)+1)
  print("all samples:", len(df))

  ### selects model features
  model_include_cols = [
      "scientific_name", "observer_id", "Id", "month_number", "year_number", "sample_id",
      "observation_count", "protocol_type", "number_observers", "longitude", "latitude"
  ]
  model_cols = [col for col in df.columns if col not in model_include_cols]

  x_train = df[model_cols].copy()
  y_train = df["observation_count"].copy()

  group_train = df[["observer_id"]].copy()

  assert len(x_train) == len(y_train) == len(group_train)

  print("Train:", x_train.shape)
  print("Train observers:", group_train["observer_id"].nunique())
  print("X train NA:", x_train.isna().sum().sum())
  print("Y train NA:", pd.isna(y_train).sum())

  X_train_np = x_train.to_numpy(dtype=np.float64)
  y_train_np = np.asarray(y_train, dtype=np.float64)
  group_train_np = group_train.astype(str).to_numpy()

  gp_model = gpb.GPModel(
    group_data=group_train_np,
    likelihood="negative_binomial" #"gaussian" "negative_binomial"
  )

  train_data = gpb.Dataset(
      data=X_train_np,
      label=y_train_np,
      feature_name=list(x_train.columns)
  )

  params = {
      "learning_rate": 0.03,
      "num_leaves": 31,
      "max_depth": -1,
      "min_data_in_leaf": 100,

      "feature_fraction": 0.7,

      "lambda_l1": 0.0,
      "lambda_l2": 1.0,

      "bagging_freq": 0,

      "verbose": 0,
      "seed": 42
  }

  ### fitting model
  model = gpb.train(
      params=params,
      train_set=train_data,
      gp_model=gp_model,
      num_boost_round=700
  )

  cov_pars = gp_model.get_cov_pars()
  print(cov_pars)
  re_train = model.predict_training_data_random_effects()

  re_check = pd.DataFrame({
    "observer_id": df["observer_id"].values,
    "observer_re": re_train["Group_1"].values,
  })

  print(re_check.groupby("observer_id")["observer_re"].nunique().value_counts())
  print(re_check.head())

  ### model performance
  pred_train = model.predict(
    data=X_train_np,
    group_data_pred=group_train_np,
    predict_response=True
  )

  y_pred_train = np.asarray(
      pred_train["response_mean"]
  ).reshape(-1)

  src_train, _ = spearmanr(
      y_train_np,
      y_pred_train
  )

  mae_train = mean_absolute_error(
      y_train_np,
      y_pred_train
  )

  print("Model SRC:", src_train)
  print("Model MAE:", mae_train)


  ### feature importance
  importance_df = pd.DataFrame({
    "feature": model.feature_name(),
    "importance": model.feature_importance(
        importance_type="gain"
    )
  })

  importance_df["importance"] = (
      importance_df["importance"] /
      importance_df["importance"].sum()
  )

  importance_df = importance_df.sort_values(
      "importance",
      ascending=False
  ).reset_index(drop=True)

  print(importance_df)


  ### reconstruction Abundance
  valid_ids = df["Id"].unique()
  recon_df = env[env["Id"].isin(valid_ids)].copy()
  recon_df = recon_df[recon_df["year_number"].isin([2021, 2022])].copy()

  print("df unique Id:", df["Id"].nunique())
  print("recon unique Id:", recon_df["Id"].nunique())
  print("recon rows:", len(recon_df))

  reference_duration = df["duration_mins"].median()
  reference_effort = df["effort_km"].median()
  reference_locality = df["locality_type"].mode()[0]

  recon_df["duration_mins"] = reference_duration
  recon_df["effort_km"] = reference_effort
  recon_df["locality_type"] = reference_locality

  missing_cols = [col for col in model_cols if col not in recon_df.columns]
  if len(missing_cols) > 0:
      raise ValueError(f"recon_df ???? model features: {missing_cols}")

  X_recon = recon_df[model_cols].copy()

  print("Number of reconstruction samples:", len(X_recon))
  print("Number of features:", X_recon.shape[1])
  print("Feature order same as training:", list(X_recon.columns) == list(x_train.columns))

  if list(X_recon.columns) != list(x_train.columns):
      raise ValueError("X_recon feature columns/order ? x_train ???")

  print("NA count:", X_recon.isna().sum().sum())
  #numeric_recon = X_recon.select_dtypes(include=[np.number])
  #print("Inf count:", np.isinf(numeric_recon.to_numpy()).sum())

  X_recon_np = X_recon.to_numpy(dtype=np.float64)

  pred_recon = model.predict(
    data=X_recon_np,
    ignore_gp_model=True
  )
  recon_df["birdname"] = bird_name
  recon_df["relative_abundance"] = pred_recon
  recon_df["reference_duration_mins"] = reference_duration
  recon_df["reference_effort_km"] = reference_effort
  recon_df["reference_locality_type"] = reference_locality

  print("===== Reconstruction summary =====")
  print(recon_df["relative_abundance"].describe())


  ### output result
  output_root = "/content/drive/MyDrive/gpboost_abundance_outputs"
  os.makedirs(output_root, exist_ok=True)

  bird_slug = re.sub(
      r"[^A-Za-z0-9._-]+",
      "_",
      bird_name
  ).strip("_")

  bird_output_dir = os.path.join(output_root, bird_slug)
  os.makedirs(bird_output_dir, exist_ok=True)

  reconstruction_path = os.path.join(
      bird_output_dir,
      f"{bird_slug}_reconstruction_abundance.csv"
  )

  feature_importance_path = os.path.join(
      bird_output_dir,
      f"{bird_slug}_feature_importance_gain.csv"
  )

  performance_path = os.path.join(
      bird_output_dir,
      f"{bird_slug}_model_performance.csv"
  )

  random_effect_path = os.path.join(
      bird_output_dir,
      f"{bird_slug}_random_effect.csv"
  )

  cov_pars_path = os.path.join(
      bird_output_dir,
      f"{bird_slug}_random_effect_cov_pars.csv"
  )

  recon_df.to_csv(reconstruction_path, index=False)
  importance_df.to_csv(feature_importance_path, index=False)
  re_check.to_csv(random_effect_path, index=False)

  performance_df = pd.DataFrame([{
      "birdname": bird_name,
      "n_train": len(df),
      "train Spearman SRC": src_train,
      "train MAE": mae_train,
  }])

  performance_df.to_csv(performance_path, index=False)

  cov_pars_df = pd.DataFrame(cov_pars)
  cov_pars_df.to_csv(cov_pars_path, index=False)

  zip_path = os.path.join(
      output_root,
      f"{bird_slug}_outputs.zip"
  )

  with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
      for file_path in [
          reconstruction_path,
          feature_importance_path,
          performance_path,
          random_effect_path,
          cov_pars_path,
      ]:
          zipf.write(
              file_path,
              arcname=os.path.basename(file_path)
          )

  print("Saved CSV files to:", bird_output_dir)
  print("Saved zip file:", zip_path)

